---
version: 2.1

orbs:
  # Replace this with your own!
  auto_ci: dylanhitt/ci-auto-orb@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0
  docker: circleci/docker@2.0.1

parameters:
  run-integration-tests:
    description: >
      An internal flag to prevent integration test
      from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow"
      job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"
  image-version:
    description: >
      The development image version
    type: string
    default: "dev:alpha"

dev-filters: &dev-filters
  filters:
    branches:
      ignore: master
    tags:
      ignore: /.*/

master-filters: &master-filters
  filters:
    branches:
      only: master

workflows:
  development:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint:
          <<: *dev-filters
      - orb-tools/pack:
          <<: *dev-filters
      - docker/publish:
          <<: *dev-filters
          image: dylanhitt1/nowsecure-auto
          tag: ${CIRCLE_SHA1:0:7}
      - orb-tools/publish-dev:
          orb-name: dylanhitt/ci-auto-orb
          context: General
          <<: *dev-filters
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - docker/publish
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: General
          <<: *dev-filters
          pipeline-param-map: >-
            {\"run-integration-tests\": true, \"dev-orb-version\":
            \"dev:${CIRCLE_SHA1:0:7}\", \"image-version\":
            \"${CIRCLE_SHA1:0:7}\"}
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test

  stable:
    jobs:
      - promote-image:
          <<: *master-filters
          pull_tag: ${CIRCLE_SHA1:0:7}
          push_tag: stable

jobs:

  integration-test:
    docker:
      - image: dylanhitt1/nowsecure-auto:<<pipeline.parameters.image-version>>
    steps:
      - run:
          name: Get APK file
          command: |
            curl -L \
            https://github.com/bitbar/test-samples/raw/master/apps/android/bitbar-sample-app.apk \
            -o app.apk
      - auto_ci/mobile_security_test:
          file: app.apk
          score: "0"
          show_status_messages: "true"

  promote-image:
    parameters:
      pull_tag:
        type: string
      push_tag:
        type: string
    environment:
      IMAGE_NAME: dylanhitt1/nowsecure-auto
    executor: docker/machine
    steps:
      - docker/check
      - docker/pull:
          images: '${IMAGE_NAME}:<< parameters.pull_tag >>'
      - docker/push:
          image: ${IMAGE_NAME}
          tag: << parameters.push_tag >>"
